name: Build API Image.
on:
  push:
    branches:
      - development
    paths:
      - 'src/**'

  workflow_dispatch:
defaults:
  run:
    working-directory: ./
jobs:
  deploy_api_on_openshift:
    if: github.repository_owner == 'bcgov'
    runs-on: ubuntu-latest
    steps:
      - name: Login to OpenShift and open the correct namespace
        uses: redhat-developer/openshift-actions@v1.1
        with:
          version: 'latest'
          openshift_server_url: ${{ secrets.OpenShiftServerURL }}
          parameters: '{"apitoken": "${{ secrets.OpenShiftToken }}", "acceptUntrustedCerts": "true"}'
          cmd: |
            oc project ${{ secrets.OpenShiftNamespace }}
      - name: Create PipelineRun
        run: |
          cat <<EOF | oc create -f -
            apiVersion: tekton.dev/v1beta1
            kind: PipelineRun
            metadata:
              generateName: send-message-pipelinerun-
              namespace: ${{ secrets.OpenShiftNamespace }}
              labels:
                tekton.dev/pipeline: send-message-pipeline
            spec:
              params:
                - name: rocketchat-url-secret
                  value: rocketchat-url
              pipelineRef:
                name: send-message-pipeline
              serviceAccountName: pipeline
              timeouts:
                pipeline: 1h0m0s
          EOF
